apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store-app
  labels:
    app: kv-store-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kv-store-app
  template:
    metadata:
      labels:
        app: kv-store-app
    spec:
      containers:
      - name: kv-store-app
        image: ozblech/kv-store-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kv-store-app-service
spec:
  type: NodePort
  selector:
    app: kv-store-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30007